"""Add api_key to platforms table

Revision ID: 2b7f42778f26
Revises: e2f50b6cce16
Create Date: 2025-09-07 16:05:02.273357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b7f42778f26'
down_revision: Union[str, None] = 'e2f50b6cce16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platforms', sa.Column('api_key', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'platforms', ['api_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'platforms', type_='unique')
    op.drop_column('platforms', 'api_key')
    # ### end Alembic commands ###
